[package]
name = "laminafs-sys"
version = "0.1.0"
authors = ["Brett Lajzer <brett@brettlajzer.com>"]
edition = "2018"
links = "laminafs"

[build-dependencies]
bindgen = "0.46.0"
cc = "1.0.28"

[dependencies]
